// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: proto/kubexrecommendation.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KubexRecommendation is the top-level message for a recommendation.
type KubexRecommendation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind            string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace       string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	OwnerReferences []*OwnerReference      `protobuf:"bytes,4,rep,name=owner_references,json=ownerReferences,proto3" json:"owner_references,omitempty"`
	Containers      []*Container           `protobuf:"bytes,5,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KubexRecommendation) Reset() {
	*x = KubexRecommendation{}
	mi := &file_proto_kubexrecommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubexRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubexRecommendation) ProtoMessage() {}

func (x *KubexRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kubexrecommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubexRecommendation.ProtoReflect.Descriptor instead.
func (*KubexRecommendation) Descriptor() ([]byte, []int) {
	return file_proto_kubexrecommendation_proto_rawDescGZIP(), []int{0}
}

func (x *KubexRecommendation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubexRecommendation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *KubexRecommendation) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubexRecommendation) GetOwnerReferences() []*OwnerReference {
	if x != nil {
		return x.OwnerReferences
	}
	return nil
}

func (x *KubexRecommendation) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

// Container represents the recommendation details for a single container within a workload.
type Container struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	Container            string                  `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	EntityId             string                  `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	ContainerId          string                  `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	AutomationEnabled    bool                    `protobuf:"varint,4,opt,name=automation_enabled,json=automationEnabled,proto3" json:"automation_enabled,omitempty"`
	SuspendAutomation    bool                    `protobuf:"varint,5,opt,name=suspend_automation,json=suspendAutomation,proto3" json:"suspend_automation,omitempty"`
	SuspendedOn          *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=suspended_on,json=suspendedOn,proto3" json:"suspended_on,omitempty"`
	HpaScalingMetrics    []string                `protobuf:"bytes,7,rep,name=hpa_scaling_metrics,json=hpaScalingMetrics,proto3" json:"hpa_scaling_metrics,omitempty"`
	RecommendedResources []*RecommendedResources `protobuf:"bytes,8,rep,name=recommended_resources,json=recommendedResources,proto3" json:"recommended_resources,omitempty"`
	AnalyzedOn           *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=analyzed_on,json=analyzedOn,proto3" json:"analyzed_on,omitempty"`
	CurrentResources     []*RecommendedResources `protobuf:"bytes,10,rep,name=current_resources,json=currentResources,proto3" json:"current_resources,omitempty"`
	OwnerSpecs           *OwnerSpecs             `protobuf:"bytes,11,opt,name=owner_specs,json=ownerSpecs,proto3" json:"owner_specs,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_proto_kubexrecommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kubexrecommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_proto_kubexrecommendation_proto_rawDescGZIP(), []int{1}
}

func (x *Container) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *Container) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Container) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *Container) GetAutomationEnabled() bool {
	if x != nil {
		return x.AutomationEnabled
	}
	return false
}

func (x *Container) GetSuspendAutomation() bool {
	if x != nil {
		return x.SuspendAutomation
	}
	return false
}

func (x *Container) GetSuspendedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.SuspendedOn
	}
	return nil
}

func (x *Container) GetHpaScalingMetrics() []string {
	if x != nil {
		return x.HpaScalingMetrics
	}
	return nil
}

func (x *Container) GetRecommendedResources() []*RecommendedResources {
	if x != nil {
		return x.RecommendedResources
	}
	return nil
}

func (x *Container) GetAnalyzedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.AnalyzedOn
	}
	return nil
}

func (x *Container) GetCurrentResources() []*RecommendedResources {
	if x != nil {
		return x.CurrentResources
	}
	return nil
}

func (x *Container) GetOwnerSpecs() *OwnerSpecs {
	if x != nil {
		return x.OwnerSpecs
	}
	return nil
}

// OwnerSpecs holds the specifications at the level of the pod owner.
type OwnerSpecs struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	CurrentSpec    []*RecommendedResources `protobuf:"bytes,1,rep,name=current_spec,json=currentSpec,proto3" json:"current_spec,omitempty"`
	PreviousSpec   []*RecommendedResources `protobuf:"bytes,2,rep,name=previous_spec,json=previousSpec,proto3" json:"previous_spec,omitempty"`
	SpecChangeDate *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=spec_change_date,json=specChangeDate,proto3" json:"spec_change_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OwnerSpecs) Reset() {
	*x = OwnerSpecs{}
	mi := &file_proto_kubexrecommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnerSpecs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerSpecs) ProtoMessage() {}

func (x *OwnerSpecs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kubexrecommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerSpecs.ProtoReflect.Descriptor instead.
func (*OwnerSpecs) Descriptor() ([]byte, []int) {
	return file_proto_kubexrecommendation_proto_rawDescGZIP(), []int{2}
}

func (x *OwnerSpecs) GetCurrentSpec() []*RecommendedResources {
	if x != nil {
		return x.CurrentSpec
	}
	return nil
}

func (x *OwnerSpecs) GetPreviousSpec() []*RecommendedResources {
	if x != nil {
		return x.PreviousSpec
	}
	return nil
}

func (x *OwnerSpecs) GetSpecChangeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.SpecChangeDate
	}
	return nil
}

// RecommendedResources holds the request and limit values for a resource.
type RecommendedResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *ResourceLimit         `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Limit         *ResourceLimit         `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendedResources) Reset() {
	*x = RecommendedResources{}
	mi := &file_proto_kubexrecommendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendedResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedResources) ProtoMessage() {}

func (x *RecommendedResources) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kubexrecommendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedResources.ProtoReflect.Descriptor instead.
func (*RecommendedResources) Descriptor() ([]byte, []int) {
	return file_proto_kubexrecommendation_proto_rawDescGZIP(), []int{3}
}

func (x *RecommendedResources) GetRequest() *ResourceLimit {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RecommendedResources) GetLimit() *ResourceLimit {
	if x != nil {
		return x.Limit
	}
	return nil
}

// ResourceLimit defines the CPU and Memory values.
type ResourceLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimit) Reset() {
	*x = ResourceLimit{}
	mi := &file_proto_kubexrecommendation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimit) ProtoMessage() {}

func (x *ResourceLimit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kubexrecommendation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimit.ProtoReflect.Descriptor instead.
func (*ResourceLimit) Descriptor() ([]byte, []int) {
	return file_proto_kubexrecommendation_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceLimit) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ResourceLimit) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

// OwnerReference identifies the owner of a Kubernetes object.
type OwnerReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnerReference) Reset() {
	*x = OwnerReference{}
	mi := &file_proto_kubexrecommendation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnerReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerReference) ProtoMessage() {}

func (x *OwnerReference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kubexrecommendation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerReference.ProtoReflect.Descriptor instead.
func (*OwnerReference) Descriptor() ([]byte, []int) {
	return file_proto_kubexrecommendation_proto_rawDescGZIP(), []int{5}
}

func (x *OwnerReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OwnerReference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

var File_proto_kubexrecommendation_proto protoreflect.FileDescriptor

const file_proto_kubexrecommendation_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/kubexrecommendation.proto\x12\x05model\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x01\n" +
	"\x13KubexRecommendation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12@\n" +
	"\x10owner_references\x18\x04 \x03(\v2\x15.model.OwnerReferenceR\x0fownerReferences\x120\n" +
	"\n" +
	"containers\x18\x05 \x03(\v2\x10.model.ContainerR\n" +
	"containers\"\xc3\x04\n" +
	"\tContainer\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\tR\tcontainer\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\x12-\n" +
	"\x12automation_enabled\x18\x04 \x01(\bR\x11automationEnabled\x12-\n" +
	"\x12suspend_automation\x18\x05 \x01(\bR\x11suspendAutomation\x12=\n" +
	"\fsuspended_on\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vsuspendedOn\x12.\n" +
	"\x13hpa_scaling_metrics\x18\a \x03(\tR\x11hpaScalingMetrics\x12P\n" +
	"\x15recommended_resources\x18\b \x03(\v2\x1b.model.RecommendedResourcesR\x14recommendedResources\x12;\n" +
	"\vanalyzed_on\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"analyzedOn\x12H\n" +
	"\x11current_resources\x18\n" +
	" \x03(\v2\x1b.model.RecommendedResourcesR\x10currentResources\x122\n" +
	"\vowner_specs\x18\v \x01(\v2\x11.model.OwnerSpecsR\n" +
	"ownerSpecs\"\xd4\x01\n" +
	"\n" +
	"OwnerSpecs\x12>\n" +
	"\fcurrent_spec\x18\x01 \x03(\v2\x1b.model.RecommendedResourcesR\vcurrentSpec\x12@\n" +
	"\rprevious_spec\x18\x02 \x03(\v2\x1b.model.RecommendedResourcesR\fpreviousSpec\x12D\n" +
	"\x10spec_change_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0especChangeDate\"r\n" +
	"\x14RecommendedResources\x12.\n" +
	"\arequest\x18\x01 \x01(\v2\x14.model.ResourceLimitR\arequest\x12*\n" +
	"\x05limit\x18\x02 \x01(\v2\x14.model.ResourceLimitR\x05limit\"9\n" +
	"\rResourceLimit\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\tR\x06memory\"8\n" +
	"\x0eOwnerReference\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kindB9Z7github.com/densify-dev/container-automation-model/modelb\x06proto3"

var (
	file_proto_kubexrecommendation_proto_rawDescOnce sync.Once
	file_proto_kubexrecommendation_proto_rawDescData []byte
)

func file_proto_kubexrecommendation_proto_rawDescGZIP() []byte {
	file_proto_kubexrecommendation_proto_rawDescOnce.Do(func() {
		file_proto_kubexrecommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kubexrecommendation_proto_rawDesc), len(file_proto_kubexrecommendation_proto_rawDesc)))
	})
	return file_proto_kubexrecommendation_proto_rawDescData
}

var file_proto_kubexrecommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_kubexrecommendation_proto_goTypes = []any{
	(*KubexRecommendation)(nil),   // 0: model.KubexRecommendation
	(*Container)(nil),             // 1: model.Container
	(*OwnerSpecs)(nil),            // 2: model.OwnerSpecs
	(*RecommendedResources)(nil),  // 3: model.RecommendedResources
	(*ResourceLimit)(nil),         // 4: model.ResourceLimit
	(*OwnerReference)(nil),        // 5: model.OwnerReference
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_kubexrecommendation_proto_depIdxs = []int32{
	5,  // 0: model.KubexRecommendation.owner_references:type_name -> model.OwnerReference
	1,  // 1: model.KubexRecommendation.containers:type_name -> model.Container
	6,  // 2: model.Container.suspended_on:type_name -> google.protobuf.Timestamp
	3,  // 3: model.Container.recommended_resources:type_name -> model.RecommendedResources
	6,  // 4: model.Container.analyzed_on:type_name -> google.protobuf.Timestamp
	3,  // 5: model.Container.current_resources:type_name -> model.RecommendedResources
	2,  // 6: model.Container.owner_specs:type_name -> model.OwnerSpecs
	3,  // 7: model.OwnerSpecs.current_spec:type_name -> model.RecommendedResources
	3,  // 8: model.OwnerSpecs.previous_spec:type_name -> model.RecommendedResources
	6,  // 9: model.OwnerSpecs.spec_change_date:type_name -> google.protobuf.Timestamp
	4,  // 10: model.RecommendedResources.request:type_name -> model.ResourceLimit
	4,  // 11: model.RecommendedResources.limit:type_name -> model.ResourceLimit
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_kubexrecommendation_proto_init() }
func file_proto_kubexrecommendation_proto_init() {
	if File_proto_kubexrecommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kubexrecommendation_proto_rawDesc), len(file_proto_kubexrecommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_kubexrecommendation_proto_goTypes,
		DependencyIndexes: file_proto_kubexrecommendation_proto_depIdxs,
		MessageInfos:      file_proto_kubexrecommendation_proto_msgTypes,
	}.Build()
	File_proto_kubexrecommendation_proto = out.File
	file_proto_kubexrecommendation_proto_goTypes = nil
	file_proto_kubexrecommendation_proto_depIdxs = nil
}
